### ISSUE TITLE
Add List of Members

### ISSUE THREAD

**Issue by theikalman** [majalengkadev/majalengkadev.github.io#1]
Hi @IhwanID , I think it would be cool if we show list of members here in this github page. What do you think?

**Comment by theikalman** [comment]
I'll do it if you don't mind. But with _not-so-cool_ UI 😃

**Comment by IhwanID** [comment]
nice idea. are we still wanna use static web and host in github pages or we use static web generator like gatsby js, hexo or jekyll and hosting it in netlify for free?

**Comment by theikalman** [comment]
That one is also pop up on top of my head but, let's just make it simple for now.
However, this doesn't mean we prevent any member to do it. Please do it, but make it simple enough so that new member can do contribute without much hassle up front.
I just don't want newcomer feeling intimidated when they sees our repos 😃

**Comment by IhwanID** [comment]
i see :) , let's get started and i guess we need to create README.md / CONTRIBUTE.md so our member can contribute and know the step by step like using git for clone, create branch, commit, push and pull request to master. IMHO

**Comment by theikalman** [comment]
The list of member has been updated here b91d0d125f65236ac8860f385c126ca7b01367ed
